baseURL = "http://xn----ctbhbcabhmli2ake3ct5aa3l5a.xn--p1ai/"
languageCode = "ru-RU"
title = "Сталинские расстрельные списки"
theme = "charaka"
copyright = """1989-2020 &copy; Международный Мемориал.<br/>
При использовании любых материалов сайта ссылка на memo.ru обязательна.<br/>
<br/>
4&nbsp;октября 2016&nbsp;года Минюст РФ&nbsp;внес Международный Мемориал в&nbsp;реестр «некоммерческих организаций, выполняющих функцию иностранного&nbsp;агента». <a target="_blank" href="https://www.memo.ru/ru-ru/memorial/departments/intermemorial/news/22">Мы&nbsp;обжалуем это решение&nbsp;в&nbsp;суде</a>.<br/>
<br/>
Техническая часть сайта &mdash; <a href="https://ru.itpp.dev/">Айти&#8209;Проджектс&nbsp;Лабс</a>.
"""

[params.elasticsearch]
    #url = "http://localhost:9200/"
    #url = "http://ec2-3-89-71-224.compute-1.amazonaws.com:9200/"
    url = "http://xn----ctbhbcabhmli2ake3ct5aa3l5a.xn--p1ai/"

[params.spravki]
    edit_url = "https://github.com/itpp-labs/stalin/edit/master/hugo/data/spravki/{FILENAME}.yaml"
    new_url = "https://github.com/itpp-labs/stalin/new/master/hugo/data/spravki/new?filename={FILENAME}.yaml&value={BODY}"
    new_body = """
- repyear: 19XX
  fio: ФАМИЛИЯ ИМЯ ОТЧЕСТВО
  source: ИСТОЧНИК
  spravka: |
    ПЕРВАЯ СТРОКА СПРАВКИ
    ВТОРАЯ СТРОКА СПРАВКИ"""
