baseURL = "https://stalin.lamourism.com/"
languageCode = "ru-RU"
title = "Сталинские расстрельные списки"
theme = "charaka"
copyright = """1989-2020 &copy; Международный Мемориал.<br/>
При использовании любых материалов сайта ссылка на memo.ru обязательна.<br/>
4&nbsp;октября 2016&nbsp;года Минюст РФ&nbsp;внес Международный Мемориал в&nbsp;реестр «некоммерческих организаций, выполняющих функцию иностранного&nbsp;агента». <a target="_blank" href="https://www.memo.ru/ru-ru/memorial/departments/intermemorial/news/22">Мы&nbsp;обжалуем это решение&nbsp;в&nbsp;суде</a>.<br/>
Техническая часть сайта &mdash; 000&nbsp;<a href="https://thepiratecircus.com/">Овуляция 🪬 Колобка</a>.
<br/><img src="/memo.svg"/>
"""

[params.elasticsearch]
    url = "https://odoomagic.lamourism.com/"

[params.spravki]
    edit_url = "https://github.com/itpp-labs/stalin/edit/master/hugo/data/spravki/{FILENAME}.yaml"
    new_url = "https://github.com/itpp-labs/stalin/new/master/hugo/data/spravki/new?filename={FILENAME}.yaml&value={BODY}"
    new_body = """
- repyear: 19XX
  fio: ФАМИЛИЯ ИМЯ ОТЧЕСТВО
  source: ИСТОЧНИК
  spravka: |
    ПЕРВАЯ СТРОКА СПРАВКИ
    ВТОРАЯ СТРОКА СПРАВКИ"""
